# Generated by Django 2.0 on 2018-05-08 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circuit_id', models.CharField(max_length=256, unique=True)),
                ('mep_id', models.CharField(max_length=256)),
                ('cir_AtoZ', models.IntegerField()),
                ('cir_ZtoA', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('state', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=256)),
                ('hw_version', models.CharField(max_length=256)),
                ('ip_type', models.CharField(choices=[('A', 'A'), ('Z', 'Z')], max_length=256)),
                ('circuit_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restApiCreation.Circuit')),
            ],
        ),
        migrations.AddField(
            model_name='circuit',
            name='customer_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restApiCreation.Customer'),
        ),
    ]
