# Generated by Django 2.0 on 2018-05-08 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restApiCreation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuit',
            name='customer_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restApiCreation.Customer'),
        ),
        migrations.AlterField(
            model_name='site',
            name='circuit_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restApiCreation.Circuit'),
        ),
    ]
