# Generated by Django 2.0 on 2018-05-15 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restApiCreation', '0002_auto_20180508_1036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='circuit',
            old_name='cir_AtoZ',
            new_name='cir_az',
        ),
        migrations.RenameField(
            model_name='circuit',
            old_name='cir_ZtoA',
            new_name='cir_za',
        ),
        migrations.RenameField(
            model_name='circuit',
            old_name='customer_fk',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='circuit_fk',
            new_name='circuit',
        ),
    ]
